# CyberShield

## Database Connectivity

In [1]:
import sqlite3
import pandas as pd

## Load Engineered Dataset

In [2]:
data = pd.read_csv("../output/engineered_dataset.csv")

print(data.shape)

data.head()

(145222, 17)

,ackdat,synack,dload,tcprtt,dmean,rate,sbytes,dbytes,smean,dinpkt,dur,sload,sinpkt,djit,sjit,label,attack_cat
0,-0.682211,-0.599759,-0.367413,-0.692397,-0.537041,-0.242915,-0.061763,-0.129779,-0.528779,-0.096566,-0.237501,-0.183584,-0.089948,-0.178936,-0.136807,0,6
1,-0.682211,-0.599759,-0.208811,-0.692397,2.924532,-0.242862,-0.059690,0.089099,-0.493230,-0.090415,-0.138246,-0.183615,-0.083601,0.120559,-0.136103,0,6
2,0.244910,0.339636,-0.350616,0.322327,2.006222,-0.243648,-0.061301,-0.061702,-0.516930,-0.014325,0.044557,-0.183651,-0.038524,2.304421,0.249938,0,6
3,-0.682211,-0.599759,-0.369059,-0.692397,-0.468656,-0.243655,-0.060151,-0.126651,-0.493230,-0.025221,0.055547,-0.183645,-0.058094,0.905024,-0.131645,0,6
4,0.369810,0.487734,-0.368857,0.471810,-0.530528,-0.243413,-0.060561,-0.129277,-0.489280,-0.037925,-0.175897,-0.183614,-0.084137,-0.156304,-0.083007,0,6

## Create SQLite Database

In [3]:
connection = sqlite3.connect("../database/cybershield.db")

cursor = connection.cursor()

print("Database Connected Successfully")

Database Connected Successfully

## Store Dataset in Database

In [4]:
data.to_sql(
    "network_data",
    connection,
    if_exists="replace",
    index=False
)

print("Dataset Stored Successfully")

Dataset Stored Successfully

## Display Available Tables

In [5]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, connection)

                   name
0          incident_log
1       sqlite_sequence
2  protection_incidents
3          network_data

## Retrieve Dataset

In [6]:
query = """
SELECT *
FROM network_data
LIMIT 10;
"""

pd.read_sql(query, connection)

,ackdat,synack,dload,tcprtt,dmean,rate,sbytes,dbytes,smean,dinpkt,dur,sload,sinpkt,djit,sjit,label,attack_cat
0,-0.682211,-0.599759,-0.367413,-0.692397,-0.537041,-0.242915,-0.061763,-0.129779,-0.528779,-0.096566,-0.237501,-0.183584,-0.089948,-0.178936,-0.136807,0,6
1,-0.682211,-0.599759,-0.208811,-0.692397,2.924532,-0.242862,-0.059690,0.089099,-0.493230,-0.090415,-0.138246,-0.183615,-0.083601,0.120559,-0.136103,0,6
2,0.244910,0.339636,-0.350616,0.322327,2.006222,-0.243648,-0.061301,-0.061702,-0.516930,-0.014325,0.044557,-0.183651,-0.038524,2.304421,0.249938,0,6
3,-0.682211,-0.599759,-0.369059,-0.692397,-0.468656,-0.243655,-0.060151,-0.126651,-0.493230,-0.025221,0.055547,-0.183645,-0.058094,0.905024,-0.131645,0,6
4,0.369810,0.487734,-0.368857,0.471810,-0.530528,-0.243413,-0.060561,-0.129277,-0.489280,-0.037925,-0.175897,-0.183614,-0.084137,-0.156304,-0.083007,0,6
5,0.303068,1.224234,-0.368626,0.875833,-0.530528,-0.243340,-0.060561,-0.129277,-0.489280,-0.058335,-0.188842,-0.183605,-0.086075,-0.163543,-0.087339,0,6
6,0.681681,0.456995,-0.368888,0.607437,-0.533785,-0.243495,-0.060561,-0.128827,-0.489280,-0.033150,-0.140649,-0.183627,-0.079054,-0.155517,-0.040813,0,6
7,0.373228,0.305045,-0.368612,0.365111,-0.533785,-0.243423,-0.060561,-0.128827,-0.489280,-0.046296,-0.162348,-0.183620,-0.082145,-0.155618,-0.052456,0,6
8,0.281893,0.411094,-0.368671,0.382967,-0.533785,-0.243439,-0.060561,-0.128827,-0.489280,-0.044505,-0.158344,-0.183622,-0.081050,-0.158306,-0.045915,0,6
9,-0.226030,0.364979,-0.367916,0.105021,-0.530528,-0.243112,-0.060561,-0.129277,-0.489280,-0.069782,-0.211729,-0.183580,-0.089153,-0.169061,-0.105607,0,6

## Retrieve Attack Records

In [7]:
query = """
SELECT *
FROM network_data
WHERE label = 1
LIMIT 10;
"""

pd.read_sql(query, connection)

,ackdat,synack,dload,tcprtt,dmean,rate,sbytes,dbytes,smean,dinpkt,dur,sload,sinpkt,djit,sjit,label,attack_cat
0,-0.682211,-0.599759,-0.370135,-0.692397,-0.677067,1.115811,-0.062016,-0.130679,-0.303635,-0.103866,-0.260317,0.289309,-0.095964,-0.181511,-0.137488,1,1
1,-0.682211,-0.599759,-0.370135,-0.692397,-0.677067,1.115811,-0.062016,-0.130679,-0.303635,-0.103866,-0.260317,0.289309,-0.095964,-0.181511,-0.137488,1,1
2,-0.682211,-0.599759,-0.370135,-0.692397,-0.677067,1.115811,-0.062016,-0.130679,-0.303635,-0.103866,-0.260317,0.289309,-0.095964,-0.181511,-0.137488,1,1
3,-0.682211,-0.599759,-0.370135,-0.692397,-0.677067,3.835077,-0.062016,-0.130679,-0.303635,-0.103866,-0.260318,1.235245,-0.095966,-0.181511,-0.137488,1,1
4,-0.682211,-0.599759,-0.370135,-0.692397,-0.677067,1.285765,-0.062016,-0.130679,-0.303635,-0.103866,-0.260317,0.348430,-0.095965,-0.181511,-0.137488,1,1
5,-0.682211,-0.599759,-0.370135,-0.692397,-0.677067,2.203518,-0.062016,-0.130679,-0.303635,-0.103866,-0.260318,0.667684,-0.095965,-0.181511,-0.137488,1,1
6,-0.682211,-0.599759,-0.370135,-0.692397,-0.677067,1.285765,-0.062016,-0.130679,-0.303635,-0.103866,-0.260317,0.348430,-0.095965,-0.181511,-0.137488,1,1
7,-0.682211,-0.599759,-0.370135,-0.692397,-0.677067,2.203518,-0.062016,-0.130679,-0.303635,-0.103866,-0.260318,0.667684,-0.095965,-0.181511,-0.137488,1,1
8,-0.682211,-0.599759,-0.370135,-0.692397,-0.677067,1.285765,-0.062016,-0.130679,-0.303635,-0.103866,-0.260317,0.348430,-0.095965,-0.181511,-0.137488,1,1
9,-0.682211,-0.599759,-0.370135,-0.692397,-0.677067,5.874527,-0.062016,-0.130679,-0.303635,-0.103866,-0.260318,1.944698,-0.095966,-0.181511,-0.137488,1,1

## Retrieve Normal Traffic

In [8]:
query = """
SELECT *
FROM network_data
WHERE label = 0
LIMIT 10;
"""

pd.read_sql(query, connection)

,ackdat,synack,dload,tcprtt,dmean,rate,sbytes,dbytes,smean,dinpkt,dur,sload,sinpkt,djit,sjit,label,attack_cat
0,-0.682211,-0.599759,-0.367413,-0.692397,-0.537041,-0.242915,-0.061763,-0.129779,-0.528779,-0.096566,-0.237501,-0.183584,-0.089948,-0.178936,-0.136807,0,6
1,-0.682211,-0.599759,-0.208811,-0.692397,2.924532,-0.242862,-0.059690,0.089099,-0.493230,-0.090415,-0.138246,-0.183615,-0.083601,0.120559,-0.136103,0,6
2,0.244910,0.339636,-0.350616,0.322327,2.006222,-0.243648,-0.061301,-0.061702,-0.516930,-0.014325,0.044557,-0.183651,-0.038524,2.304421,0.249938,0,6
3,-0.682211,-0.599759,-0.369059,-0.692397,-0.468656,-0.243655,-0.060151,-0.126651,-0.493230,-0.025221,0.055547,-0.183645,-0.058094,0.905024,-0.131645,0,6
4,0.369810,0.487734,-0.368857,0.471810,-0.530528,-0.243413,-0.060561,-0.129277,-0.489280,-0.037925,-0.175897,-0.183614,-0.084137,-0.156304,-0.083007,0,6
5,0.303068,1.224234,-0.368626,0.875833,-0.530528,-0.243340,-0.060561,-0.129277,-0.489280,-0.058335,-0.188842,-0.183605,-0.086075,-0.163543,-0.087339,0,6
6,0.681681,0.456995,-0.368888,0.607437,-0.533785,-0.243495,-0.060561,-0.128827,-0.489280,-0.033150,-0.140649,-0.183627,-0.079054,-0.155517,-0.040813,0,6
7,0.373228,0.305045,-0.368612,0.365111,-0.533785,-0.243423,-0.060561,-0.128827,-0.489280,-0.046296,-0.162348,-0.183620,-0.082145,-0.155618,-0.052456,0,6
8,0.281893,0.411094,-0.368671,0.382967,-0.533785,-0.243439,-0.060561,-0.128827,-0.489280,-0.044505,-0.158344,-0.183622,-0.081050,-0.158306,-0.045915,0,6
9,-0.226030,0.364979,-0.367916,0.105021,-0.530528,-0.243112,-0.060561,-0.129277,-0.489280,-0.069782,-0.211729,-0.183580,-0.089153,-0.169061,-0.105607,0,6

## Count Normal and Attack Records

In [9]:
query = """
SELECT
label,
COUNT(*) AS Total
FROM network_data
GROUP BY label;
"""

pd.read_sql(query, connection)

   label  Total
0      0  79965
1      1  65257

## Count Attack Categories

In [10]:
query = """
SELECT
attack_cat,
COUNT(*) AS Total
FROM network_data
GROUP BY attack_cat
ORDER BY Total DESC;
"""

pd.read_sql(query, connection)

   attack_cat  Total
0           6  79965
1           3  26749
2           4  18313
3           7   8012
4           2   4873
5           5   3057
6           0   1442
7           1   1389
8           8   1257
9           9    165

## Create Incident Log Table

In [11]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS incident_log (

incident_id INTEGER PRIMARY KEY AUTOINCREMENT,

attack_type TEXT,

threat_level TEXT,

recommended_action TEXT,

status TEXT,

timestamp DATETIME DEFAULT CURRENT_TIMESTAMP

)
""")

connection.commit()

print("Incident Log Table Created")

Incident Log Table Created

## View Incident Log Table

In [12]:
query = """
SELECT *
FROM incident_log;
"""

pd.read_sql(query, connection)

Empty DataFrame
Columns: [incident_id, attack_type, threat_level, recommended_action, status, timestamp]
Index: []

## Close Database Connection

In [13]:
connection.close()

print("Database Closed Successfully")

Database Closed Successfully